name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest

    steps:
    - name: Check PR title format
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
          perf
        requireScope: false

  pr-size-check:
    name: PR Size Check
    runs-on: ubuntu-latest

    steps:
    - name: Check PR size
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const additions = pr.additions;
          const deletions = pr.deletions;
          const total = additions + deletions;
          
          let label = '';
          let color = '';
          
          if (total < 100) {
            label = 'size/XS';
            color = '3CBF00';
          } else if (total < 300) {
            label = 'size/S';
            color = '5D9801';
          } else if (total < 500) {
            label = 'size/M';
            color = 'DFAB01';
          } else if (total < 1000) {
            label = 'size/L';
            color = 'FE6E01';
          } else {
            label = 'size/XL';
            color = 'FE0101';
          }
          
          // Add label
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            labels: [label]
          });
          
          // Add comment if PR is too large
          if (total > 1000) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `⚠️ This PR is quite large (${total} lines changed). Consider breaking it into smaller PRs for easier review.`
            });
          }

  conflict-check:
    name: Conflict Check
    runs-on: ubuntu-latest

    steps:
    - name: Check for merge conflicts
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          
          if (pr.mergeable === false) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '⚠️ This PR has merge conflicts that need to be resolved before merging.'
            });
          }

  auto-label:
    name: Auto Label PR
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🏷️ Label based on changed files
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

